apiVersion: v1
kind: Service
metadata:
  name: rl-learner
  labels:
    app: rl-learner
spec:
  type: NodePort
  ports:
  - port: 65432
    targetPort: 65432
    nodePort: 30003
  selector:
    app: rl-learner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rl-learner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rl-learner
  template:
    metadata:
      labels:
        app: rl-learner
    spec:
      containers:
        - name: rl-learner
          image: rifqifatih/rl_learner
          imagePullPolicy: Always
          ports:
          - containerPort: 65432